services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    cap_add:
      - NET_ADMIN
    environment:
      - GID=${PGID:-1000}
      # Instala as coleções de regras do Nginx e vulnerabilidades web comuns
      - COLLECTIONS=${CROWDSEC_COLLECTIONS}
      - TZ=${TIMEZONE:-Etc/UTC}
      - CUSTOM_HOSTNAME=crowdsec-swag
      - BOUNCER_KEY_cs-swag-bouncer=${BOUNCER_KEY}
      - ENROLL_KEY=${ENROLL_KEY}
      - ENROLL_INSTANCE_NAME=Swag
    volumes:
      - ${APPS_BASE_FOLDER:-./appdata}${CROWDSEC_DATA_FOLDER:-/crowdsec/data}:/var/lib/crowdsec/data:rw
      - ${APPS_BASE_FOLDER:-./appdata}${CROWDSEC_CONFIG_FOLDER:-/crowdsec/config}:/etc/crowdsec:rw
      - ${APPS_BASE_FOLDER:-./appdata}${SWAG_CONFIG_FOLDER:-/swag/config}/log/nginx:/var/log/nginx:ro
    restart: always
    security_opt:
      - no-new-privileges=true
    networks:
      local:
        ipv4_address: 172.${SUBNET_NUMBER:-20}.0.3

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - URL=${DOMAIN_URL}
      - SUBDOMAINS=wildcard
      - CERTPROVIDER=letsencrypt
      - VALIDATION=dns
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - EMAIL=${EMAIL}
      - FAIL2BAN=false
      - DOCKER_MODS=linuxserver/mods:swag-crowdsec
      - CROWDSEC_LAPI_URL=http://crowdsec:8080
      - CROWDSEC_API_KEY=${BOUNCER_KEY}
      - CROWDSEC_CAPTCHA_PROVIDER=${CROWDSEC_CAPTCHA_PROVIDER}
      - CROWDSEC_SITE_KEY=${CROWDSEC_CAPTCHA_SITE_KEY}
      - CROWDSEC_SECRET_KEY=${CROWDSEC_CAPTCHA_SECRET_KEY}
    volumes:
      - ${APPS_BASE_FOLDER:-./appdata}${SWAG_CONFIG_FOLDER:-/swag/config}:/config:rw
    restart: always
    depends_on:
      - crowdsec
    ports:
      - "80:80"
      - "443:443"
    networks:
      local:
        ipv4_address: 172.${SUBNET_NUMBER:-20}.0.2

  backup:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing-backups
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ${SYNCTHING_CONFIG_FOLDER:-./syncthing/config}:/config
      - ${APPS_BASE_FOLDER:-./appdata}:/data
    restart: always
    networks:
      local:
        ipv4_address: 172.${SUBNET_NUMBER:-20}.0.4

networks:
  local:
    name: swag-local-network
    ipam:
      config:
        - subnet: 172.${SUBNET_NUMBER:-20}.0.0/16
