services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    cap_add:
      - NET_ADMIN
    environment:
      - GID=${PGID:-1000}
      # Instala as coleções de regras do Nginx e vulnerabilidades web comuns
      - COLLECTIONS=${CROWDSEC_COLLECTIONS}
    volumes:
      - ./configs/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ENROLL_KEY=${CROWDSEC_ENROLL_KEY}
      - ENROLL_INSTANCE_NAME=Swag
      - ${CROWDSEC_DATA_FOLDER:-./data/crowdsec}:/var/lib/crowdsec/data
      - ${SWAG_DATA_FOLDER:-./data/swag}/log/nginx:/var/log/nginx:ro
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${CROWDSEC_IP}

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - URL=${DOMAIN_URL}
      - SUBDOMAINS=wildcard
      - CERTPROVIDER=letsencrypt
      - VALIDATION=dns
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - EMAIL=${EMAIL}
      - FAIL2BAN=false
      - DOCKER_MODS=linuxserver/mods:swag-crowdsec
      - CROWDSEC_LAPI_URL=http://${CROWDSEC_IP}:8080
      - CROWDSEC_API_KEY=${BOUNCER_KEY}
      - CROWDSEC_CAPTCHA_PROVIDER=${CROWDSEC_CAPTCHA_PROVIDER}
      - CROWDSEC_SITE_KEY=${CROWDSEC_CAPTCHA_SITE_KEY}
      - CROWDSEC_SECRET_KEY=${CROWDSEC_CAPTCHA_SECRET_KEY}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    volumes:
      - ./configs/nginx/default.conf:/config/nginx/site-confs/default.conf:ro
      - ./configs/cloudflare.ini:/config/dns-conf/cloudflare.ini:ro
      - ${SWAG_DATA_FOLDER:-./data/swag}:/config
    restart: unless-stopped
    depends_on:
      - crowdsec
    networks:
      external:
        ipv4_address: ${SWAG_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}
