services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    environment:
      - GID=${PGID:-1000}
      # Instala as coleções de regras do Nginx e vulnerabilidades web comuns
      - COLLECTIONS=${CROWDSEC_COLLECTIONS}
    volumes:
      - ./configs/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./data/crowdsec:/var/lib/crowdsec/data
      - ./data/swag/log/nginx:/var/log/nginx:ro
    restart: unless-stopped
    networks:
      local:

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - URL=${DOMAIN_URL}
      - SUBDOMAINS=wildcard
      - CERTPROVIDER=letsencrypt
      - VALIDATION=dns
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - EMAIL=${EMAIL}
      - FAIL2BAN=false
      - DOCKER_MODS=linuxserver/mods:swag-crowdsec
      - CROWDSEC_LAPI_URL=http://crowdsec:8080
      - CROWDSEC_API_KEY=${BOUNCER_KEY:-bouncer_key}
    volumes:
      - ./data/swag:/config
    restart: unless-stopped
    depends_on:
      - crowdsec
    ports:
      - '80:80'
      - '443:443'
      - '2082:80'
      - '8443:443'
    networks:
      local:

  crowdsec-webui:
    image: ghcr.io/theduffman85/crowdsec-web-ui
    container_name: crowdsec-webui
    environment:
      - CROWDSEC_URL=http://crowdsec:8080
      - CROWDSEC_USER=admin
      - CROWDSEC_PASSWORD=${CROWDSEC_WEBUI_PASSWORD}
    volumes:
      - ./data/crowdsec-webui:/app/data
    restart: unless-stopped
    depends_on:
      - crowdsec
    ports:
      - '3000:3000'
    networks:
      local:

networks:
  local:
    name: swag-network