services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    cap_add:
      - NET_ADMIN
    environment:
      - GID=${PGID:-1000}
      # Instala as coleções de regras do Nginx e vulnerabilidades web comuns
      - COLLECTIONS=${CROWDSEC_COLLECTIONS}
      - TZ=${TIMEZONE:-Etc/UTC}
      - CUSTOM_HOSTNAME=crowdsec-swag
      - BOUNCER_KEY_cs-swag-bouncer=${BOUNCER_KEY}
      - ENROLL_KEY=${ENROLL_KEY}
      - ENROLL_INSTANCE_NAME=Swag
    volumes:
      - ${CROWDSEC_DATA_FOLDER:-./container_data/crowdsec/data}:/var/lib/crowdsec/data
      - ${CROWDSEC_CONFIG_FOLDER:-./container_data/crowdsec/config}:/etc/crowdsec
      - ${SWAG_CONFIG_FOLDER:-./container_data/swag/config}/log/nginx:/var/log/nginx:ro
    restart: always
    networks:
      external:
        ipv4_address: ${CROWDSEC_IP}

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - URL=${DOMAIN_URL}
      - SUBDOMAINS=wildcard
      - CERTPROVIDER=letsencrypt
      - VALIDATION=dns
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - EMAIL=${EMAIL}
      - FAIL2BAN=false
      - DOCKER_MODS=linuxserver/mods:swag-crowdsec
      - CROWDSEC_LAPI_URL=http://${CROWDSEC_IP}:8080
      - CROWDSEC_API_KEY=${BOUNCER_KEY}
      - CROWDSEC_CAPTCHA_PROVIDER=${CROWDSEC_CAPTCHA_PROVIDER}
      - CROWDSEC_SITE_KEY=${CROWDSEC_CAPTCHA_SITE_KEY}
      - CROWDSEC_SECRET_KEY=${CROWDSEC_CAPTCHA_SECRET_KEY}
    volumes:
      - ${SWAG_CONFIG_FOLDER:-./container_data/swag/config}:/config
    restart: always
    depends_on:
      - crowdsec
    networks:
      external:
        ipv4_address: ${SWAG_IP}

  backup:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing-backups
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ${SYNCTHING_CONFIG_FOLDER:-./syncthing/config}:/config
      - ${APPS_BASE_FOLDER:-./appdata}:/data
    restart: always
    networks:
      external:
        ipv4_address: ${SYNCTHING_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}
